#!/bin/sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

echo -e "${GREEN}Running pre-push hook...${RESET}"

# Получаем список измененных файлов
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
CHANGED_FILES=$(git diff --cached --name-only)

HOME="$(git rev-parse --show-toplevel)"

echo -e "${BLUE}Changes in 'frontend' directory detected.${RESET}"

echo -e "${GREEN}[|] Running formatted and build for client...${RESET}"
cd ./frontend
pnpm format
pnpm build

git add .
echo -e "${GREEN}[+] Success formatted and build for client!${RESET}"
cd "$HOME"

echo -e "${BLUE}Changes in 'server.http' directory detected.${RESET}"

echo -e "${GREEN}[|] Running formatted and build for server.http...${RESET}"
cd ./server.admrc.http

make fmt
# make check
# make lint

# make build

git add .
echo -e "${GREEN}[+] Success formatted and build for server.http!${RESET}"
cd "$HOME"

echo -e "${BLUE}Changes in 'server.tcp' directory detected.${RESET}"

echo -e "${GREEN}[|] Running formatted and build for server.tcp...${RESET}"
cd ./server.admrc.tcp

make fmt
# make check
# make lint

# make build

git add .
echo -e "${GREEN}[+] Success formatted and build for server.tcp!${RESET}"
cd "$HOME"

git add .
# git commit -m "build 'binary files' for release/push bin/*"
echo -e "${GREEN}Husky is successfully!${RESET}"
